server:
  port: 6776
spring:
  application:
    name: account-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/accounts?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: true
#        namespace: f46bbdaa-f11e-414f-9530-e6a18cbf91f6
      config:
        server-addr: 127.0.0.1:8848
        enabled: true
        file-extension: yaml
#        namespace: f46bbdaa-f11e-414f-9530-e6a18cbf91f6
    sentinel:
      transport:
        dashboard: localhost:8880
        port: 8719
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:6772

seata:
  enabled: true
  application-id: ${spring.application.name}
  # 事务群组（可以每个应用独立取名，也可以使用相同的名字），要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    # 需要和server在同一个注册中心下
    nacos:
#      namespace: f46bbdaa-f11e-414f-9530-e6a18cbf91f6
      serverAddr: 127.0.0.1:8848
      # 需要server端(registry和config)、nacos配置client端(registry和config)保持一致
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      # 需要和server端保持一致，即server在nacos中的名称，默认为seata-server
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
#      namespace: f46bbdaa-f11e-414f-9530-e6a18cbf91f6
      username: "nacos"
      password: "nacos"
#mybatis-plus:
#  mapper-locations: classpath:com/cm/account/mapper/xml/*
#mybatis:
#  mapperLocations: classpath:mapper/*.xml
management:
  # 端点信息接口使用的端口，为了和主系统接口使用的端口进行分离
  server:
    port: 7059
    servlet:
      context-path: /sys
  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
  endpoint:
    health:
      show-details: always
  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.alibaba.nacos.client.config.impl: WARN
  config: classpath:logback-spring.xml
  file:
    path: logs/boot-admin.log