server:
  port: 6772
spring:
  application:
    name: buisness-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/integral?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: true
      #        namespace: f46bbdaa-f11e-414f-9530-e6a18cbf91f6
      config:
        server-addr: 127.0.0.1:8848
        enabled: true
        file-extension: yaml
  mail:
    host: smtp.qq.com
    username: 1446525549@qq.com
    password: oekwibllwkxfhcga
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true
#        namespace: f46bbdaa-f11e-414f-9530-e6a18cbf91f6
seata:
  enabled: true
  application-id: ${spring.application.name}
  # 事务群组（可以每个应用独立取名，也可以使用相同的名字），要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    # 需要和server在同一个注册中心下
    nacos:
      #      namespace: f46bbdaa-f11e-414f-9530-e6a18cbf91f6
      serverAddr: 127.0.0.1:8848
      # 需要server端(registry和config)、nacos配置client端(registry和config)保持一致
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      # 需要和server端保持一致，即server在nacos中的名称，默认为seata-server
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      #      namespace: f46bbdaa-f11e-414f-9530-e6a18cbf91f6
      username: "nacos"
      password: "nacos"
#  rocketmq.name-server=192.168.224.120:9876
#  rocketmq.producer.group=my-group
rocketmq:
  name-server: 192.168.224.120:9876
  producer:
    group: producer-demo2

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#feign:
#  hystrix:
#    enabled: true
#mybatis:
#  mapperLocations: classpath:mapper/*.xml
logging:
  level:
    root: info
    com.alibaba.nacos.client.config.impl: WARN